// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/metrics/metrics.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric представляет одну метрику
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`               // имя метрики
	Mtype         string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`         // тип: "gauge" или "counter"
	Value         *float64               `protobuf:"fixed64,3,opt,name=value,proto3,oneof" json:"value,omitempty"` // значение для gauge
	Delta         *int64                 `protobuf:"varint,4,opt,name=delta,proto3,oneof" json:"delta,omitempty"`  // значение для counter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Metric) GetDelta() int64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

// Запрос на обновление метрик (batch)
type UpdateMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsRequest) Reset() {
	*x = UpdateMetricsRequest{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsRequest) ProtoMessage() {}

func (x *UpdateMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Ответ на обновление
type UpdateMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMetricsResponse) Reset() {
	*x = UpdateMetricsResponse{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetricsResponse) ProtoMessage() {}

func (x *UpdateMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetricsResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateMetricsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Запрос на получение метрики
type GetMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mtype         string                 `protobuf:"bytes,2,opt,name=mtype,proto3" json:"mtype,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricRequest) Reset() {
	*x = GetMetricRequest{}
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricRequest) ProtoMessage() {}

func (x *GetMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricRequest.ProtoReflect.Descriptor instead.
func (*GetMetricRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GetMetricRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMetricRequest) GetMtype() string {
	if x != nil {
		return x.Mtype
	}
	return ""
}

var File_proto_metrics_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_metrics_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/metrics/metrics.proto\x12\ametrics\"x\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype\x12\x19\n" +
	"\x05value\x18\x03 \x01(\x01H\x00R\x05value\x88\x01\x01\x12\x19\n" +
	"\x05delta\x18\x04 \x01(\x03H\x01R\x05delta\x88\x01\x01B\b\n" +
	"\x06_valueB\b\n" +
	"\x06_delta\"A\n" +
	"\x14UpdateMetricsRequest\x12)\n" +
	"\ametrics\x18\x01 \x03(\v2\x0f.metrics.MetricR\ametrics\"G\n" +
	"\x15UpdateMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x10GetMetricRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05mtype\x18\x02 \x01(\tR\x05mtype2\xcb\x01\n" +
	"\x0eMetricsService\x120\n" +
	"\fUpdateMetric\x12\x0f.metrics.Metric\x1a\x0f.metrics.Metric\x12N\n" +
	"\rUpdateMetrics\x12\x1d.metrics.UpdateMetricsRequest\x1a\x1e.metrics.UpdateMetricsResponse\x127\n" +
	"\tGetMetric\x12\x19.metrics.GetMetricRequest\x1a\x0f.metrics.MetricB\x19Z\x17gometrics/proto/metricsb\x06proto3"

var (
	file_proto_metrics_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_metrics_proto_rawDescData []byte
)

func file_proto_metrics_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_metrics_proto_rawDescData
}

var file_proto_metrics_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_metrics_metrics_proto_goTypes = []any{
	(*Metric)(nil),                // 0: metrics.Metric
	(*UpdateMetricsRequest)(nil),  // 1: metrics.UpdateMetricsRequest
	(*UpdateMetricsResponse)(nil), // 2: metrics.UpdateMetricsResponse
	(*GetMetricRequest)(nil),      // 3: metrics.GetMetricRequest
}
var file_proto_metrics_metrics_proto_depIdxs = []int32{
	0, // 0: metrics.UpdateMetricsRequest.metrics:type_name -> metrics.Metric
	0, // 1: metrics.MetricsService.UpdateMetric:input_type -> metrics.Metric
	1, // 2: metrics.MetricsService.UpdateMetrics:input_type -> metrics.UpdateMetricsRequest
	3, // 3: metrics.MetricsService.GetMetric:input_type -> metrics.GetMetricRequest
	0, // 4: metrics.MetricsService.UpdateMetric:output_type -> metrics.Metric
	2, // 5: metrics.MetricsService.UpdateMetrics:output_type -> metrics.UpdateMetricsResponse
	0, // 6: metrics.MetricsService.GetMetric:output_type -> metrics.Metric
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metrics_metrics_proto_init() }
func file_proto_metrics_metrics_proto_init() {
	if File_proto_metrics_metrics_proto != nil {
		return
	}
	file_proto_metrics_metrics_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_metrics_proto_rawDesc), len(file_proto_metrics_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrics_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_metrics_proto = out.File
	file_proto_metrics_metrics_proto_goTypes = nil
	file_proto_metrics_metrics_proto_depIdxs = nil
}
