// Code generated by mockery v2.53.5. DO NOT EDIT.

package retry

import mock "github.com/stretchr/testify/mock"

// MockAction is an autogenerated mock type for the Action type
type MockAction struct {
	mock.Mock
}

// Execute provides a mock function with given fields: args
func (_m *MockAction) Execute(args ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(...interface{}) (interface{}, error)); ok {
		return rf(args...)
	}
	if rf, ok := ret.Get(0).(func(...interface{}) interface{}); ok {
		r0 = rf(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAction creates a new instance of MockAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAction {
	mock := &MockAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
